
package client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IGradeImplService", targetNamespace = "http://iGradeService/", wsdlLocation = "http://localhost:8282/iGrade?wsdl")
public class IGradeImplService
    extends Service
{

    private final static URL IGRADEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException IGRADEIMPLSERVICE_EXCEPTION;
    private final static QName IGRADEIMPLSERVICE_QNAME = new QName("http://iGradeService/", "IGradeImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8282/iGrade?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        IGRADEIMPLSERVICE_WSDL_LOCATION = url;
        IGRADEIMPLSERVICE_EXCEPTION = e;
    }

    public IGradeImplService() {
        super(__getWsdlLocation(), IGRADEIMPLSERVICE_QNAME);
    }

    public IGradeImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), IGRADEIMPLSERVICE_QNAME, features);
    }

    public IGradeImplService(URL wsdlLocation) {
        super(wsdlLocation, IGRADEIMPLSERVICE_QNAME);
    }

    public IGradeImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, IGRADEIMPLSERVICE_QNAME, features);
    }

    public IGradeImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IGradeImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IGradeService
     */
    @WebEndpoint(name = "IGradeImplPort")
    public IGradeService getIGradeImplPort() {
        return super.getPort(new QName("http://iGradeService/", "IGradeImplPort"), IGradeService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IGradeService
     */
    @WebEndpoint(name = "IGradeImplPort")
    public IGradeService getIGradeImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://iGradeService/", "IGradeImplPort"), IGradeService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (IGRADEIMPLSERVICE_EXCEPTION!= null) {
            throw IGRADEIMPLSERVICE_EXCEPTION;
        }
        return IGRADEIMPLSERVICE_WSDL_LOCATION;
    }

}
