CREATE TABLE "STUDENT" (
"LASTNAME" VARCHAR(30),
"FIRSTNAME" VARCHAR(30),
"STUDENTID" VARCHAR(10) not null primary key,
"TEAMNUMBER" VARCHAR(60)
);
INSERT INTO STUDENT VALUES ('Baker','Austin','ARB5671','3');
INSERT INTO STUDENT VALUES ('Balos','Amanda','AZB199','1');
INSERT INTO STUDENT VALUES ('Balta','Trent','TMB5577','12');
INSERT INTO STUDENT VALUES ('Campbell','Matthew','MRC5372','10');
INSERT INTO STUDENT VALUES ('Duong','Charlie','CTD5100','8');
INSERT INTO STUDENT VALUES ('Goga','Daniel','DRG5190','11');
INSERT INTO STUDENT VALUES ('Hankewycz','Andrew','AZH5442','7');
INSERT INTO STUDENT VALUES ('Hansen','Robert','RAH5360','8');
INSERT INTO STUDENT VALUES ('Ivanco','Justin','JJI5019','10');
INSERT INTO STUDENT VALUES ('Jacobs','Tyler','TAJ5130','7');
INSERT INTO STUDENT VALUES ('Jones','Edward','EAJ5073','6');
INSERT INTO STUDENT VALUES ('Kalmer','Peter','PJK5220','3');
INSERT INTO STUDENT VALUES ('Kelleher','Austin','ALK5492','7');
INSERT INTO STUDENT VALUES ('Kruzan','Andrew','ASK5264','4');
INSERT INTO STUDENT VALUES ('Kubacki','David','DMK5048','5');
INSERT INTO STUDENT VALUES ('Lin','Gary','GQL5141','6');
INSERT INTO STUDENT VALUES ('Louchart','Gregory','GDL5051','2');
INSERT INTO STUDENT VALUES ('Orosz','Zachary','ZJO5002','6');
INSERT INTO STUDENT VALUES ('Panetta','Matthew','MDP5280','9');
INSERT INTO STUDENT VALUES ('Poljak','Dylan','DJP5319','4');
INSERT INTO STUDENT VALUES ('Rausch','Austin','AHR5067','12');
INSERT INTO STUDENT VALUES ('Arin','Reese','AWR5319','11');
INSERT INTO STUDENT VALUES ('Reott','Zachary','ZDR5063','6');
INSERT INTO STUDENT VALUES ('Ristau','Brian','BJR5336','2');
INSERT INTO STUDENT VALUES ('Ristau','Steven','SPR5122','2');
INSERT INTO STUDENT VALUES ('Rosswog','Christopher','CMR5556','10');
INSERT INTO STUDENT VALUES ('Schultz','James','JTS5507','8');
INSERT INTO STUDENT VALUES ('Sitterly','Shaun','SMS6179','4');
INSERT INTO STUDENT VALUES ('Stankiewicz','Mark','MIS5708','9');
INSERT INTO STUDENT VALUES ('Steen','Joshua','JDS5782','9');
INSERT INTO STUDENT VALUES ('Tarosky','Kimbery','KRT5110','1');
INSERT INTO STUDENT VALUES ('Taylor','Dylan','DMT5235','3');
INSERT INTO STUDENT VALUES ('Vallo','Alexander','ANV5067','2');
INSERT INTO STUDENT VALUES ('Wilczek','Conner','CVW5203','6');
