
package clientSOAP;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UserManagerService", targetNamespace = "http://managementService/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserManagerService {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllLoggedUsers", targetNamespace = "http://managementService/", className = "clientSOAP.GetAllLoggedUsers")
    @ResponseWrapper(localName = "getAllLoggedUsersResponse", targetNamespace = "http://managementService/", className = "clientSOAP.GetAllLoggedUsersResponse")
    @Action(input = "http://managementService/UserManagerService/getAllLoggedUsersRequest", output = "http://managementService/UserManagerService/getAllLoggedUsersResponse")
    public String getAllLoggedUsers();

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "logInUser", targetNamespace = "http://managementService/", className = "clientSOAP.LogInUser")
    @ResponseWrapper(localName = "logInUserResponse", targetNamespace = "http://managementService/", className = "clientSOAP.LogInUserResponse")
    @Action(input = "http://managementService/UserManagerService/logInUserRequest", output = "http://managementService/UserManagerService/logInUserResponse")
    public boolean logInUser(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "logOutUser", targetNamespace = "http://managementService/", className = "clientSOAP.LogOutUser")
    @ResponseWrapper(localName = "logOutUserResponse", targetNamespace = "http://managementService/", className = "clientSOAP.LogOutUserResponse")
    @Action(input = "http://managementService/UserManagerService/logOutUserRequest", output = "http://managementService/UserManagerService/logOutUserResponse")
    public boolean logOutUser(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "registerUser", targetNamespace = "http://managementService/", className = "clientSOAP.RegisterUser")
    @ResponseWrapper(localName = "registerUserResponse", targetNamespace = "http://managementService/", className = "clientSOAP.RegisterUserResponse")
    @Action(input = "http://managementService/UserManagerService/registerUserRequest", output = "http://managementService/UserManagerService/registerUserResponse")
    public boolean registerUser(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
